

[general]
# import = [
#   "/usr/lib/node_modules/alacritty-themes/themes/Afterglow.toml"
# ]
#  import = [
#     "~/.config/alacritty/themes/themes/alabaster.toml"
# ]

[window]
opacity = 1
blur = true

[selection]
save_to_clipboard = true

[font.normal]
# family = "Marck Script" 
family = "JetBrainsMono NF"
# family = "Source Code Pro"
# family = "fuck fuck"
# family = "JetBrainsMono NFM"
# style = ""

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"

# [colors.primary]
# background = "#fafafa"
# foreground = "#383a42"

# [colors.normal]
# black   = "#000000"
# red     = "#e45649"
# green   = "#50a14f"
# yellow  = "#c18401"
# blue    = "#4078f2"
# magenta = "#a626a4"
# cyan    = "#0184bc"
# white   = "#a0a1a7"

# [colors.bright]
# black   = "#7c7c7c"
# red     = "#e06c75"
# green   = "#98c379"
# yellow  = "#d19a66"
# blue    = "#61afef"
# magenta = "#c678dd"
# cyan    = "#56b6c2"
# white   = "#ffffff"

